#!/usr/bin/env bash
#This is to install my loadbalancer

sudo apt-get -y update
sudo apt-get -y install haproxy

# Replace HAProxy config
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend skomaiya_frontend
    bind *:80
    mode http
    default_backend skomaiya_backend

backend skomaiya_backend
    balance roundrobin
    server web-01 50.19.28.95:80 check
    server web-02 34.228.9.239:80 check
EOF

# Enable HAProxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Validate and restart
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart

# Output for checker
echo "Configured HAProxy to route traffic to web-01 and web-02"
